### ISSUE TITLE
datasets是不是沒有開放了?

### ISSUE THREAD

**Issue by salierilovegura** [aaron1aaron2/Crop-Image-Classification#6]
想請問datasets是不是不能下載了?
謝謝!!

**Comment by aaron1aaron2** [comment]
是的，之前整理雲端時有刪掉檔案，這邊再重新上傳資料到雲端。

下面連結包含測試用的 100 筆資料(sample100_L160(test).zip) 和有有降低畫質的全部資料(predata.zip)。

https://drive.google.com/drive/folders/1PT_A76Hxx2oINN3SGdKh8Hf-k7b4Iiqq?usp=drive_link

因原始資料太大(約 170 G) 所以目前不提供。

**Comment by aaron1aaron2** [comment]
連結已關閉，有需要資料再寄信問我:

aaron1aaron2@gmail.com
